name : Genm

on : [push]

jobs:
   file-check:
    runs-on: ubuntu-latest
    steps: 
      - name: up to date code
        uses: actions/checkout@v4

      - name: Status index.html
        run: 
          if [ -f "index.html" ]; then
            echo "Aman!"
          else 
            echo "ga aman!"
            exit 1
          fi
